@startuml

title Client - Server communication

participant Client
participant Server

== Initialization ==
Client -[#blue]> Server : Version
Client <[#blue]- Server : CheckedVersion
alt incompatible versions
    Client <-[#red]- Server : close socket
    destroy Client
    destroy Server
end
Client <[#blue]- Server : GameInfo
alt  Game full
    Client <-[#red]- Server : close socket
    destroy Client
    destroy Server
end

== Login ==
loop ALREADY_EXISTS status
    Client -[#blue]> Server : PlayerLogin
    Client <[#blue]- Server : PlayerLoginStatus
end

alt  GAME_FULL status
    Client <-[#red]- Server : close socket
    destroy Client
    destroy Server
end

Client <[#green]- Server : PlayersInfo N

== Game ==
Client <[#green]- Server : MatchInfo N
alt A player won
    Client <-[#red]- Server : close socket N
    destroy Client
    destroy Server
end
Client -[#blue]-> Server : PlayerAction
Client <[#green]- Server : Frame N

@enduml
