@startuml

title Communication
actor Player

== Connection ==

Player -> Client : InitGame
Client -> Server : ServerInfoRequest
Client <-- Server : ServerInfo

== Log in ==

loop character not allowed
    Player -> Client : ConfigureCharacter
    Client -> Server : LogIn
    Client <-- Server : LogInStatus
end

== Match ==

loop wait all players
    Client <- Server : NextMatchStatus
end
Client <- Server : LoadMap
Player <<- Client : ShowMatch

loop playing the match
    Client <- Server : Frame
    Player <<- Client : Show
    Player ->> Client : Input
    Client ->> Server : PlayerAction
end

@enduml
