@startuml


package common {
    class NetworkManager
    class PackageFactory
    class PackageQueue
    class InputPack
    class OutputPack
    'class GameSpec

    NetworkManager *-- PackageFactory
    NetworkManager o-- PackageQueue
    PackageQueue o--"0..*" InputPack
    PackageQueue o--"0..*" OutputPack
    PackageFactory -up-> InputPack
    PackageFactory -up-> OutputPack
}

package server {
    class Server
    class ServerManager
    class PlayersRoom
    class Player
    class Arena

    Server *-right- NetworkManager
    Server *-- ServerManager
    ServerManager -right-|> PackageQueue
    ServerManager *-- PlayersRoom
    ServerManager *-- Arena
    'ServerManager o-left-"0..*" GameSpec
    PlayersRoom *--"0..*" Player
}

package client {
    class MessageQueue
    class Client
    class ClientManager
    class TermScreen
    class Keyboard
    class GameScene
    class Pencil

    Client *-left- NetworkManager
    Client *-- ClientManager
    MessageQueue -left-|> PackageQueue
    ClientManager -left-|> MessageQueue
    ClientManager *-- TermScreen
    ClientManager --> GameScene
    GameScene o-- TermScreen
    TermScreen --> Pencil
    GameScene --> Pencil
    Keyboard o-- TermScreen
}

@enduml
