@startuml

title Info server

actor Client
participant Server
participant InfoServer
participant VersionChecker
participant GameServer

Server -> VersionChecker : <<new>>
Server -> GameServer : <<new>>
Server -> InfoServer : <<new>>
Server -> InfoServer : run
activate InfoServer
loop
    Client ->> InfoServer : versionMessage
    InfoServer -> InfoServer : handleVersionRequest
    activate InfoServer
    InfoServer -> VersionChecker : checkCompatibility
    activate VersionChecker
    InfoServer <- VersionChecker : checkCompatibility
    deactivate VersionChecker
    Client <<-- InfoServer : checkVersionMessage
    InfoServer -> GameServer : getGameInfo
    activate GameServer
    InfoServer <-- GameServer
    deactivate GameServer
    Client <<-- InfoServer : serverInfoMessage
    deactivate InfoServer
end
Server <-- InfoServer
deactivate InfoServer

@enduml

