@startuml

title Match server

actor Client
participant Server
participant MatchServer
participant MatchManager
participant PlayerRegistry
participant Match

Server -> MatchServer : <<new>>
Server -> MatchServer : run
activate MatchServer
MatchServer -> MatchManager : <<new>>
MatchManager -> PlayerRegistry : <<new>>
loop
    Client ->> MatchServer : <<new connection>>
    MatchServer -> MatchServer : handlePlayerConnection
    activate MatchServer
    MatchServer -> MatchManager : registerPlayer
    activate MatchManager
    Client ->> MatchManager : newPlayerMessage
    MatchManager -> PlayerRegistry : addPlayer
    activate PlayerRegistry
    MatchManager <-- PlayerRegistry : status
    deactivate PlayerRegistry
    Client <<-- MatchManager : playerConnectionStatusMessage
    Client <<-- MatchManager : playersInfoMessage (to all)
    MatchServer <-- MatchManager : status
    deactivate MatchManager
    MatchServer -> MatchManager : run
    activate MatchManager
    deactivate MatchServer
    loop until one player reaches the points to win
        MatchManager -> Match : <<new>>
        MatchManager -> MatchManager : init
        activate MatchManager
        MatchManager -> Match : generateMap
        activate Match
        MatchManager <-- Match : map
        deactivate Match
        Client <<-- MatchManager : matchInfoMessage (to all)
        deactivate MatchManager
        MatchManager -> MatchManager : play
        activate MatchManager
        loop until only one player alive
            MatchManager -> Match : computeFrame
            activate Match
            MatchManager <-- Match : frameData
            deactivate Match
            Client <<-- MatchManager : frameMessage (to all)
            Client ->> MatchManager : playerActionMessage (from all)
            MatchManager -> PlayerRegistry : checkAction
            activate PlayerRegistry
            MatchManager <-- PlayerRegistry
            deactivate PlayerRegistry
            MatchManager -> Match : userAction
            activate Match
            MatchManager <-- Match
            deactivate Match
        end
        deactivate MatchManager
    end
        MatchManager -> PlayerRegistry : removePlayers
        activate PlayerRegistry
        MatchManager <-- PlayerRegistry
        deactivate PlayerRegistry
    deactivate MatchManager
end
Server <-- MatchServer
deactivate MatchServer

@enduml
