@startuml

title Game server

actor Client
participant Server
participant GameServer
participant GameManager
participant PlayerRegistry
participant Arena

Server -> GameServer : <<new>>
Server -> GameServer : run
activate GameServer
GameServer -> GameManager : <<new>>
GameManager -> PlayerRegistry : <<new>>
loop
    Client ->> GameServer : <<new connection>>
    GameServer -> GameServer : handlePlayerConnection
    activate GameServer
    GameServer -> GameManager : registerPlayer
    activate GameManager
    Client ->> GameManager : newPlayerMessage
    GameManager -> PlayerRegistry : addPlayer
    activate PlayerRegistry
    GameManager <-- PlayerRegistry : status
    deactivate PlayerRegistry
    Client <<-- GameManager : playerConnectionStatusMessage
    Client <<-- GameManager : playersInfoMessage (to all)
    GameServer <-- GameManager : status
    deactivate GameManager
    GameServer -> GameManager : startGame
    activate GameManager
    deactivate GameServer
    loop until one player reaches the points to win
        GameManager -> Arena : <<new>>
        GameManager -> GameManager : init
        activate GameManager
        GameManager -> Arena : generateMap
        activate Arena
        GameManager <-- Arena : map
        deactivate Arena
        Client <<-- GameManager : matchInfoMessage (to all)
        loop until only one player alive
            GameManager -> Arena : computeFrame
            activate Arena
            GameManager <-- Arena : frameData
            deactivate Arena
            Client <<-- GameManager : frameMessage (to all)
            Client ->> GameManager : playerActionMessage (from all)
            GameManager -> PlayerRegistry : checkAction
            activate PlayerRegistry
            GameManager <-- PlayerRegistry
            deactivate PlayerRegistry
            GameManager -> Arena : userAction
            activate Arena
            GameManager <-- Arena
            deactivate Arena
        end
        deactivate GameManager
    end
    GameManager -> PlayerRegistry : removePlayers
    activate PlayerRegistry
    GameManager <-- PlayerRegistry
    deactivate PlayerRegistry
    deactivate GameManager
end
Server <-- GameServer
deactivate GameServer

@enduml
