@startuml

title Game server

actor Client
participant Server
participant GameServer
participant GameManager
participant PlayerRegistry
participant Arena
participant Version

-> Server : listen
Server -> GameServer : <<new>>
activate Server
activate GameServer
Client ->> Server : <<new connection>>
Client ->> Server : versionMessage
Server -> Version : check
activate Version
Server <- Version : compatibility
deactivate Version
Client <<-- Server : checkVersionMessage
Server -> GameServer : getGameInfo
activate GameServer
Server <-- GameServer
deactivate GameServer
Client <<-- Server : serverInfoMessage
deactivate Server
GameServer -> GameManager : <<new>>
GameManager -> PlayerRegistry : <<new>>
loop
    GameServer -> GameServer : playerConnection
    activate GameServer
    GameServer -> GameManager : registerPlayer
    activate GameManager
    Client ->> GameManager : newPlayerMessage
    GameManager -> PlayerRegistry : add
    activate PlayerRegistry
    GameManager <-- PlayerRegistry : status
    deactivate PlayerRegistry
    Client <<-- GameManager : playerLoginStatusMessage
    Client <<-- GameManager : playersInfoMessage (to all)
    GameServer <-- GameManager : status
    deactivate GameManager
    GameServer -> GameManager : startGame
    activate GameManager
    deactivate GameServer
    loop until one player reaches the points to win
        GameManager -> Arena : <<new>>
        GameManager -> GameManager : init
        activate GameManager
        GameManager -> Arena : generateMap
        activate Arena
        GameManager <-- Arena : map
        deactivate Arena
        Client <<-- GameManager : matchInfoMessage (to all)
        loop until only one player alive
            GameManager -> Arena : computeFrame
            activate Arena
            GameManager <-- Arena : frameData
            deactivate Arena
            Client <<-- GameManager : frameMessage (to all)
            Client ->> GameManager : playerActionMessage (from all)
            GameManager -> PlayerRegistry : checkAction
            activate PlayerRegistry
            GameManager <-- PlayerRegistry
            deactivate PlayerRegistry
            GameManager -> Arena : userAction
            activate Arena
            GameManager <-- Arena
            deactivate Arena
        end
        deactivate GameManager
    end
    GameManager -> PlayerRegistry : removePlayers
    activate PlayerRegistry
    GameManager <-- PlayerRegistry
    deactivate PlayerRegistry
    deactivate GameManager
end
Server <-- GameServer
deactivate GameServer

@enduml
