@startuml

title Server info

[-> ServerInfoManager : ServerInfoRequest
activate ServerInfoManager
ServerInfoManager -> MatchManager : RequestMatchState
activate MatchManager
MatchManager -> PlayerRegistry : RequestCurrentPlayers
activate PlayerRegistry
MatchManager <-- PlayerRegistry : CurrentPlayers
deactivate PlayerRegistry
ServerInfoManager <-- MatchManager : MatchState
deactivate MatchManager
[<-- ServerInfoManager : ServerInfo
deactivate ServerInfoManager

@enduml
