@startuml

title main_sequence

actor main

[-> MatchServer : <<New>>
MatchServer -> PlayerRegistry : <<New>>
MatchServer -> InfoServer : <<New>>

[-> MatchServer : Run
activate MatchServer
MatchServer -> InfoServer : Run
activate InfoServer
loop
    MatchServer -> MatchServer : WaitingMatch
    activate MatchServer
    deactivate MatchServer
    MatchServer -> MatchServer : InitializingMatch
    activate MatchServer
    deactivate MatchServer
    MatchServer -> MatchServer : PlayingMatch
    activate MatchServer
    deactivate MatchServer
end
MatchServer <-- InfoServer : End
deactivate InfoServer
[<-- MatchServer : End
deactivate MatchServer

@enduml
